# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hsuDataMain.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HsuDataManagementSystem(object):
    def setupUi(self, HsuDataManagementSystem):
        HsuDataManagementSystem.setObjectName("HsuDataManagementSystem")
        HsuDataManagementSystem.resize(800, 600)
        font = QtGui.QFont()
        font.setPointSize(8)
        HsuDataManagementSystem.setFont(font)
        self.centralwidget = QtWidgets.QWidget(HsuDataManagementSystem)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setMinimumSize(QtCore.QSize(0, 0))
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_3.addWidget(self.textBrowser)
        HsuDataManagementSystem.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(HsuDataManagementSystem)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuPersonnel = QtWidgets.QMenu(self.menubar)
        self.menuPersonnel.setObjectName("menuPersonnel")
        HsuDataManagementSystem.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(HsuDataManagementSystem)
        self.statusbar.setObjectName("statusbar")
        HsuDataManagementSystem.setStatusBar(self.statusbar)
        self.checkInOutWidget = QtWidgets.QDockWidget(HsuDataManagementSystem)
        self.checkInOutWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkInOutWidget.sizePolicy().hasHeightForWidth())
        self.checkInOutWidget.setSizePolicy(sizePolicy)
        self.checkInOutWidget.setFloating(False)
        self.checkInOutWidget.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.checkInOutWidget.setObjectName("checkInOutWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkInLed = QtWidgets.QLabel(self.dockWidgetContents)
        self.checkInLed.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkInLed.sizePolicy().hasHeightForWidth())
        self.checkInLed.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.checkInLed.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(24)
        font.setKerning(True)
        self.checkInLed.setFont(font)
        self.checkInLed.setLineWidth(1)
        self.checkInLed.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.checkInLed.setObjectName("checkInLed")
        self.horizontalLayout.addWidget(self.checkInLed)
        self.checkIn = QtWidgets.QPushButton(self.dockWidgetContents)
        self.checkIn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkIn.sizePolicy().hasHeightForWidth())
        self.checkIn.setSizePolicy(sizePolicy)
        self.checkIn.setCheckable(False)
        self.checkIn.setAutoExclusive(False)
        self.checkIn.setObjectName("checkIn")
        self.horizontalLayout.addWidget(self.checkIn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkOutLed = QtWidgets.QLabel(self.dockWidgetContents)
        self.checkOutLed.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkOutLed.sizePolicy().hasHeightForWidth())
        self.checkOutLed.setSizePolicy(sizePolicy)
        self.checkOutLed.setMaximumSize(QtCore.QSize(16777215, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.checkOutLed.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.checkOutLed.setFont(font)
        self.checkOutLed.setObjectName("checkOutLed")
        self.horizontalLayout_2.addWidget(self.checkOutLed)
        self.checkOut = QtWidgets.QPushButton(self.dockWidgetContents)
        self.checkOut.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkOut.sizePolicy().hasHeightForWidth())
        self.checkOut.setSizePolicy(sizePolicy)
        self.checkOut.setCheckable(False)
        self.checkOut.setObjectName("checkOut")
        self.horizontalLayout_2.addWidget(self.checkOut)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(45, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.checkInOutLine = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.checkInOutLine.setObjectName("checkInOutLine")
        self.horizontalLayout_4.addWidget(self.checkInOutLine)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.checkInOutWidget.setWidget(self.dockWidgetContents)
        HsuDataManagementSystem.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.checkInOutWidget)
        self.checkInOutToggle = QtWidgets.QAction(HsuDataManagementSystem)
        self.checkInOutToggle.setCheckable(True)
        self.checkInOutToggle.setChecked(True)
        self.checkInOutToggle.setObjectName("checkInOutToggle")
        self.menuPersonnel.addAction(self.checkInOutToggle)
        self.menubar.addAction(self.menuPersonnel.menuAction())

        self.retranslateUi(HsuDataManagementSystem)
        self.checkInOutToggle.toggled['bool'].connect(self.checkInOutWidget.setVisible)
        self.checkIn.clicked['bool'].connect(self.checkOut.setDisabled)
        self.checkOut.clicked['bool'].connect(self.checkOut.setEnabled)
        self.checkIn.clicked['bool'].connect(self.checkIn.setEnabled)
        self.checkOut.clicked['bool'].connect(self.checkIn.setDisabled)
        self.checkIn.clicked['bool'].connect(self.checkInLed.setDisabled)
        self.checkOut.clicked['bool'].connect(self.checkOutLed.setDisabled)
        self.checkIn.clicked['bool'].connect(self.checkOutLed.setEnabled)
        self.checkOut.clicked['bool'].connect(self.checkInLed.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(HsuDataManagementSystem)

    def retranslateUi(self, HsuDataManagementSystem):
        _translate = QtCore.QCoreApplication.translate
        HsuDataManagementSystem.setWindowTitle(_translate("HsuDataManagementSystem", "Hsu Data Management System"))
        self.menuPersonnel.setTitle(_translate("HsuDataManagementSystem", "Personnel"))
        self.checkInOutWidget.setWindowTitle(_translate("HsuDataManagementSystem", "Check-In/Out"))
        self.checkInLed.setText(_translate("HsuDataManagementSystem", "●"))
        self.checkIn.setText(_translate("HsuDataManagementSystem", "Check-In"))
        self.checkOutLed.setText(_translate("HsuDataManagementSystem", "●"))
        self.checkOut.setText(_translate("HsuDataManagementSystem", "Check-Out"))
        self.checkInOutToggle.setText(_translate("HsuDataManagementSystem", "Check-In/Out"))
