# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newParent.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdditionalInformation(object):
    def setupUi(self, AdditionalInformation):
        AdditionalInformation.setObjectName("AdditionalInformation")
        AdditionalInformation.resize(750, 331)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AdditionalInformation.sizePolicy().hasHeightForWidth())
        AdditionalInformation.setSizePolicy(sizePolicy)
        AdditionalInformation.setMinimumSize(QtCore.QSize(750, 331))
        AdditionalInformation.setMaximumSize(QtCore.QSize(750, 331))
        self.verticalLayout = QtWidgets.QVBoxLayout(AdditionalInformation)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.phoneNumber = QtWidgets.QLabel(AdditionalInformation)
        self.phoneNumber.setObjectName("phoneNumber")
        self.horizontalLayout.addWidget(self.phoneNumber)
        self.phone = QtWidgets.QLineEdit(AdditionalInformation)
        self.phone.setObjectName("phone")
        self.horizontalLayout.addWidget(self.phone)
        self.label_2 = QtWidgets.QLabel(AdditionalInformation)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.altPhone = QtWidgets.QLineEdit(AdditionalInformation)
        self.altPhone.setObjectName("altPhone")
        self.horizontalLayout.addWidget(self.altPhone)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(AdditionalInformation)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.email = QtWidgets.QLineEdit(AdditionalInformation)
        self.email.setObjectName("email")
        self.horizontalLayout_3.addWidget(self.email)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.line = QtWidgets.QFrame(AdditionalInformation)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(AdditionalInformation)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.position = QtWidgets.QLineEdit(AdditionalInformation)
        self.position.setObjectName("position")
        self.horizontalLayout_4.addWidget(self.position)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(AdditionalInformation)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.school = QtWidgets.QLineEdit(AdditionalInformation)
        self.school.setObjectName("school")
        self.horizontalLayout_5.addWidget(self.school)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.linkToStudent = QtWidgets.QPushButton(AdditionalInformation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.linkToStudent.sizePolicy().hasHeightForWidth())
        self.linkToStudent.setSizePolicy(sizePolicy)
        self.linkToStudent.setObjectName("linkToStudent")
        self.horizontalLayout_2.addWidget(self.linkToStudent)
        self.showStudents = QtWidgets.QTextBrowser(AdditionalInformation)
        self.showStudents.setMinimumSize(QtCore.QSize(0, 150))
        self.showStudents.setMaximumSize(QtCore.QSize(16777215, 150))
        self.showStudents.setObjectName("showStudents")
        self.horizontalLayout_2.addWidget(self.showStudents)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line_2 = QtWidgets.QFrame(AdditionalInformation)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.cancel = QtWidgets.QPushButton(AdditionalInformation)
        self.cancel.setObjectName("cancel")
        self.horizontalLayout_7.addWidget(self.cancel)
        self.confirm = QtWidgets.QPushButton(AdditionalInformation)
        self.confirm.setObjectName("confirm")
        self.horizontalLayout_7.addWidget(self.confirm)
        self.verticalLayout.addLayout(self.horizontalLayout_7)

        self.retranslateUi(AdditionalInformation)
        QtCore.QMetaObject.connectSlotsByName(AdditionalInformation)

    def retranslateUi(self, AdditionalInformation):
        _translate = QtCore.QCoreApplication.translate
        AdditionalInformation.setWindowTitle(_translate("AdditionalInformation", "Additional Information"))
        self.phoneNumber.setText(_translate("AdditionalInformation", "Phone Number: "))
        self.label_2.setText(_translate("AdditionalInformation", "Alt Phone: "))
        self.label_5.setText(_translate("AdditionalInformation", "Email: "))
        self.label.setText(_translate("AdditionalInformation", "Position: "))
        self.label_3.setText(_translate("AdditionalInformation", "School:   "))
        self.linkToStudent.setText(_translate("AdditionalInformation", "Link To Student"))
        self.cancel.setText(_translate("AdditionalInformation", "Cancel"))
        self.confirm.setText(_translate("AdditionalInformation", "Confirm"))
